package net.fzyz.jerryc05.fzyz_app.core.apis;

/**
 * API collection for yidingyigou.net
 */
@SuppressWarnings({"SpellCheckingInspection", "unused"})
public interface ApiYdyg {
  String
          URL_YDYG_HOST                   = "http://m.yidingyigou.net:9090",
          URL_MALL_CANCEL_ORDER           = "/mall/mall/cancelOrder",
          URL_MALL_CANCEL_REJECT          = "/mall/mall/cancelReject",
          URL_GOODS_CANCEL_ORDER          = "/mall/goods/cancelOrder",
          URL_GOODS_BACK_FOOD             = "/mall/goods/backFood",
          URL_GOODS_DEFAULT_SHOP_TYPO     = "/mall/goods/defaulShop",
          URL_GOODS_CHANGE_ADDRESS_TYPO   = "/mall/goods/changAddress",
          URL_MEMBER_LOGIN                = "/mall/member/login",
          URL_MEMBER_SAVE_ADDRESS         = "/mall/member/saveAddress",
          URL_MEMBER_MY_ADDRESS           = "/mall/member/myAddress",
          URL_MEMBER_CARD_LOST            = "/mall/member/cardlost",
          URL_MEMBER_UPDATE_PICTURE       = "/mall/member/updatePicture",
          URL_MEMBER_UPDATE_PASSWORD      = "/mall/member/updatePwd",
          URL_MEMBER_ALL_CITYS            = "/mall/member/allCitys",
          URL_MALL_MORE_GOODS             = "/mall/mall/moreGoods",
          URL_MALL_GOOD_COMMENT           = "/mall/mall/goodComment",
          URL_MALL_GOOD_INFO              = "/mall/mall/goodInfo",
          URL_MALL_COMFIRM_GOOD           = "/mall/mall/comfirmGood",
          URL_MEMBER_ACCOUNT_RECORD       = "/mall/member/accountrecord",
          URL_GOODS_DO_DAILY_MEAL         = "/mall/goods/dodailymeal",
          URL_MEMBER_DEL_ADDRESS          = "/mall/member/delAddress",
          URL_MEMBER_ALL_DISTRICT         = "/mall/member/allDistrict",
          URL_GOODS_HOT_FOODS             = "/mall/goods/hotFoods",
          URL_MALL_ORDER_STATUS_MALFORMED = "mall/mall/orderstatus",
          URL_MALL_ORDER_LIST             = "/mall/mall/orderList",
          URL_MEMBER_MESSAGE_DETAIL       = "/mall/member/msgDetail",
          URL_MEMBER_MEMBER_MESSAGE       = "/mall/member/memberMsg",
          URL_MEMBER_ALL_PROVINCE         = "/mall/member/allProvince",
          URL_MEMBER_RECHARGE             = "/mall/member/recharge",
          URL_MEMBER_RECHARGE_STATUS      = "/mall/member/rechargestatus",
          URL_GOODS_ORDER_LIST            = "/mall/goods/orderList",
          URL_GOODS_COOK_BOOK             = "/mall/goods/cookbook",
          URL_MALL_RECOMMEND_SHOP         = "/mall/mall/recommendShop",
          URL_GOODS_PAY_ORDER             = "/mall/goods/payOrder",
          URL_GOODS_TAKE_FOOD_LIST        = "/mall/goods/takeFoodList",
          URL_GOODS_GOURMET_FOOD          = "/mall/goods/gourmetFood",
          URL_MEMBER_MEMBER_INFO          = "/mall/member/memberInfo",
          URL_MEMBER_CURRENT_VERSION      = "/mall/member/currentVersion",
          URL_MEMBER_FEED_BACK            = "/mall/member/feedback",
          URL_MALL_ORDER_COMMENT          = "/mall/mall/orderComment",
          URL_GOODS_APPLY_MEAL_MALFORMED  = "mall/goods/applymeal",
          URL_MALL_SUBMIT_ORDER           = "/mall/mall/submitOrder",
          URL_MALL_GOOD_REJECT            = "/mall/mall/goodReject",
          URL_MALL_PAY_ORDER              = "/mall/mall/payOrder",
          URL_GOODS_TAKE_FOOD             = "/mall/goods/takeFood",
          URL_GOODS_SAVE_ORDER            = "/mall/goods/saveOrder";
}
